Tipos_pokemons = {
    "Bulbasaur": "Planta",
    "Ivysaur": "Planta",
    "Venusaur": "Planta",
    "Charmander": "Fuego",
    "Charmeleon": "Fuego",
    "Charizard": "Fuego",
    "Squirtle": "Agua",
    "Wartortle": "Agua",
    "Blastoise": "Agua",
    "Caterpie": "Bicho",
    "Metapod": "Bicho",
    "Butterfree": "Bicho",
    "Weedle": "Bicho",
    "Kakuna": "Bicho",
    "Beedrill": "Bicho",
    "Pidgey": "Normal",
    "Pidgeotto": "Normal",
    "Pidgeot": "Normal",
    "Rattata": "Normal",
    "Raticate": "Normal",
    "Spearow": "Normal",
    "Fearow": "Normal",
    "Ekans": "Veneno",
    "Arbok": "Veneno",
    "Pikachu": "Eléctrico",
    "Raichu": "Eléctrico",
    "Sandshrew": "Tierra",
    "Sandslash": "Tierra",
    "Nidoran♀": "Veneno",
    "Nidorina": "Veneno",
    "Nidoqueen": "Veneno",
    "Nidoran♂": "Veneno",
    "Nidorino": "Veneno",
    "Nidoking": "Veneno",
    "Clefairy": "Normal",
    "Clefable": "Normal",
    "Vulpix": "Fuego",
    "Ninetales": "Fuego",
    "Jigglypuff": "Normal",
    "Wigglytuff": "Normal",
    "Zubat": "Veneno",
    "Golbat": "Veneno",
    "Oddish": "Planta",
    "Gloom": "Planta",
    "Vileplume": "Planta",
    "Paras": "Bicho",
    "Parasect": "Bicho",
    "Venonat": "Bicho",
    "Venomoth": "Bicho",
    "Diglett": "Tierra",
    "Dugtrio": "Tierra",
    "Meowth": "Normal",
    "Persian": "Normal",
    "Psyduck": "Agua",
    "Golduck": "Agua",
    "Mankey": "Lucha",
    "Primeape": "Lucha",
    "Growlithe": "Fuego",
    "Arcanine": "Fuego",
    "Poliwag": "Agua",
    "Poliwhirl": "Agua",
    "Poliwrath": "Agua",
    "Abra": "Psíquico",
    "Kadabra": "Psíquico",
    "Alakazam": "Psíquico",
    "Machop": "Lucha",
    "Machoke": "Lucha",
    "Machamp": "Lucha",
    "Bellsprout": "Planta",
    "Weepinbell": "Planta",
    "Victreebel": "Planta",
    "Tentacool": "Agua",
    "Tentacruel": "Agua",
    "Geodude": "Roca",
    "Graveler": "Roca",
    "Golem": "Roca",
    "Ponyta": "Fuego",
    "Rapidash": "Fuego",
    "Slowpoke": "Agua",
    "Slowbro": "Agua",
    "Magnemite": "Eléctrico",
    "Magneton": "Eléctrico",
    "Farfetch'd": "Normal",
    "Doduo": "Normal",
    "Dodrio": "Normal",
    "Seel": "Agua",
    "Dewgong": "Agua",
    "Grimer": "Veneno",
    "Muk": "Veneno",
    "Shellder": "Agua",
    "Cloyster": "Agua",
    "Gastly": "Fantasma",
    "Haunter": "Fantasma",
    "Gengar": "Fantasma",
    "Onix": "Roca",
    "Drowzee": "Psíquico",
    "Hypno": "Psíquico",
    "Krabby": "Agua",
    "Kingler": "Agua",
    "Voltorb": "Eléctrico",
    "Electrode": "Eléctrico",
    "Exeggcute": "Planta",
    "Exeggutor": "Planta",
    "Cubone": "Tierra",
    "Marowak": "Tierra",
    "Hitmonlee": "Lucha",
    "Hitmonchan": "Lucha",
    "Lickitung": "Normal",
    "Koffing": "Veneno",
    "Weezing": "Veneno",
    "Rhyhorn": "Tierra",
    "Rhydon": "Tierra",
    "Chansey": "Normal",
    "Tangela": "Planta",
    "Kangaskhan": "Normal",
    "Horsea": "Agua",
    "Seadra": "Agua",
    "Goldeen": "Agua",
    "Seaking": "Agua",
    "Staryu": "Agua",
    "Starmie": "Agua",
    "Mr. Mime": "Psíquico",
    "Scyther": "Bicho",
    "Jynx": "Hielo",
    "Electabuzz": "Eléctrico",
    "Magmar": "Fuego",
    "Pinsir": "Bicho",
    "Tauros": "Normal",
    "Magikarp": "Agua",
    "Gyarados": "Agua",
    "Lapras": "Agua",
    "Ditto": "Normal",
    "Eevee": "Normal",
    "Vaporeon": "Agua",
    "Jolteon": "Eléctrico",
    "Flareon": "Fuego",
    "Porygon": "Normal",
    "Omanyte": "Roca",
    "Omastar": "Roca",
    "Kabuto": "Roca",
    "Kabutops": "Roca",
    "Aerodactyl": "Roca",
    "Snorlax": "Normal",
    "Articuno": "Hielo",
    "Zapdos": "Eléctrico",
    "Moltres": "Fuego",
    "Dratini": "Dragón",
    "Dragonair": "Dragón",
    "Dragonite": "Dragón",
    "Mewtwo": "Psíquico",
    "Mew": "Psíquico"
}
#Diccionario de los tipos de cada pokemon

tipos_movimientos = {
    "Ascuas": "Fuego",
    "Latigo cepa": "Planta",
    "Pistola agua": "Agua",
    "Placaje": "Normal",
    "Llamarada": "Fuego",
    "Rayo solar": "Fuego",
    "Aguijonador": "Normal",
    "Hoja Afilada": "Lucha",
    "Bloqueo": "Lucha",
    "Ataque de hielo": "Hielo",
    "Ataque de agua": "Agua",
    "Ataque de fuego": "Fuego",
    "Ataque de planta": "Planta",
    "Ataque de electricidad": "Eléctrico",
    "Ataque de lucha": "Lucha",
    "Ataque de hielo oscuro": "Siniestro",
    "Ataque de roca": "Roca",
    "Ataque de pícaro": "Pícaro",
    "Ataque de psiquiatra": "Psíquico",
    "Ataque de insecto": "Insecto",
    "Ataque de fantasma": "Fantasma",
    "Ataque de dragón": "Dragón",
    "Ataque de dragón oscuro": "Siniestro",
    "Ataque de dragón verde": "Dragón",
    "Ataque de dragón blanco": "Dragón",
} # diccionario de los tipos de cada ataque

Tipos_x2 = {
    "Planta": {"Agua", "Insecto", "Lucha"},
    "Fuego": {"Planta", "Roca", "Psíquico"},
    "Agua": {"Fuego", "Roca", "Dragón"},
    "Insecto": {"Lucha", "Psíquico"},
    "Lucha": {"Insecto", "Roca"},
    "Roca": {"Fuego", "Agua", "Lucha"},
    "Psíquico": {"Fuego", "Psíquico"},
    "Dragón": {"Agua", "Dragón"},
    "Siniestro": {"Dragón", "Siniestro"},
} # Diccionario de todos los tipos que al atacar al otro son eficazes (x2)

Tipos_x1 = {
    "Normal": {"Roca"},
    "Hielo": {"Dragón", "Hielo"},
    "Electrico": {"Dragón", "Electrico"},
    "Veneno": {"Roca", "Veneno"},
    "Hada": {"Fantasma", "Hada"},
    "Fantasma": {"Hada"},
    "Pícaro": {"Pícaro"},
    "Bicho": {"Bicho"},
    "Dinosaurio": {"Dinosaurio"},
} # Diccionario de todos los tipos que al atacar al otro son neutros (x1)

Tipos_x05 = {
    "Planta": {"Planta", "Fuego", "Dragón"},
    "Fuego": {"Fuego", "Agua", "Hielo"},
    "Agua": {"Agua", "Roca", "Hielo"},
    "Insecto": {"Insecto", "Electrico"},
    "Lucha": {"Lucha", "Psíquico"},
    "Roca": {"Roca", "Veneno"},
    "Psíquico": {"Psíquico"},
    "Dragón": {"Dragón", "Siniestro"},
    "Fantasma": {"Fantasma"},
    "Pícaro": {"Pícaro"},
    "Bicho": {"Bicho"},
    "Dinosaurio": {"Dinosaurio"},
} # Diccionario de todos los tipos que al atacar al otro son resistentes (x0.5)

tipo_de_movimientos = {
    "Especial": ["Ascuas", "Pistola agua", "Rayo", "Psíquico", "Llamarada", "Rayo solar", "Ataque de hielo", "Ataque de agua", "Ataque de fuego", "Ataque de planta", "Ataque de electricidad", "Ataque de psiquiatra", "Ataque de fantasma", "Ataque de dragón"],
    "Fisico": ["Latigo cepa", "Placaje", "Aguijonador", "Hoja Afilada", "Bloqueo", "Ataque de lucha", "Ataque de insecto", "Ataque de roca", "Ataque de pícaro"],
    "Alt_Precicion": ["Ataque arena"],
    "Alt_Evacion": ["Doble equipo"]
} # diccionario de los tipos de cada movimiento
#Diccionario de todos los tipos que al atacar al otro son resistentes(x0.5)

def Eficacia(Tipo_Atacante, Tipo_Defensor): #funcion para definir la eficacioa
    if Tipo_Defensor in Tipos_x2.get(Tipo_Atacante, []): #Dice que si Tipo del pokemon que resive el ataqe esta dentro del diccionario de x2(buscando en cada una de los sub indice) retorna 2
        return 1.8
    elif Tipo_Defensor in Tipos_x1.get(Tipo_Atacante, []): #Dice que si Tipo del pokemon que resive el ataqe esta dentro del diccionario de x1(buscando en cada una de los sub indice) retorna 1
        return 1.35
    elif Tipo_Defensor in Tipos_x05.get(Tipo_Atacante, []): #Dice que si Tipo del pokemon que resive el ataqe esta dentro del diccionario de x05(buscando en cada una de los sub indice) retorna 0.5
        return 0.8
    else:
        return 1 #en caso de que no este en ninguno de los 3 se retorna 1 para que no haya problemas con el calculo
